# Generated by Django 2.2.2 on 2020-08-07 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timesheet_date', models.DateField()),
                ('timesheet_created_date', models.DateField(auto_now_add=True, verbose_name='Created On')),
                ('is_saved', models.BooleanField(default=False, verbose_name='Saved')),
                ('shift', models.CharField(default='General', max_length=255, verbose_name='Shift')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('timesheet_date', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='Tasklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=1000, verbose_name='Task')),
                ('assigned_by', models.CharField(max_length=255, verbose_name='Assigned By')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasklist', to='timesheet_app.Timesheet')),
            ],
        ),
    ]
